<?php

$powerary=array(
"会员资料"=>array("后台会员注册","公司注册","未确认会员","会员列表","授权登录","会员查看","会员修改","查看货币明细","会员查询","前台会员升级记录","后台级别修改","级别修改","后台级别修改记录","会员申请店铺记录"),
"网络图"=>array("一线网","公排网","安置网络图","推荐网络图","安置网体修改","推荐网体修改","安置体系树状图","推荐体系树状图"),
"财务管理"=>array("财务充值","充值","银行账号","添加修改帐号","汇款管理","提现管理","会员转账","财务明细","在线支付记录"),
"奖金管理"=>array("日奖金管理","结算添加","奖金结算","执行奖金结算","奖金列表","平衡奖金","奖金发放","奖金修改"),
"查询系统"=>array("会员统计","会员数查询","日奖金查询","个人收入统计","总奖金拨出率"),
"产品管理"=>array("产品分类","分类添加","分类修改","分类删除","产品管理","产品产看","产品添加修改","入库列表","出库列表"),
"订单管理"=>array("订单列表","订单查看","订单发货","物流管理","物流修改添加"),
"信息中心"=>array("写邮件","收件箱","查看收件箱","发件箱","查看发件箱","公告管理","公告修改添加"),
"短信管理"=>array("短信余额","短信管理","短信模版","常用语设定","常用语添加修改","短信分组","分组添加修改","分组用户添加","分组用户列表","短信群发","短信发送记录"),
"数据库管理"=>array("数据库备份","数据库恢复",'数据库备份压缩','数据库备份管理','执行数据库备份',"删除备份目录"),
"系统管理"=>array("管理员设置","管理员添加修改","部门列表","部门添加修改","日志管理","区域设置","添加修改省份","所辖市列表","添加修改市","所辖区域列表","添加修改县区","奖金参数设定","参数设定","会员使用权限","前台登录页面设定","修改密码","系统初始化"));
$filesary=array(
"会员资料"=>array("userreg.php","compreg.php","users1.php","users.php","loginusrdo.php","userview.php","useredit.php","package.php","userquery.php","applystores.php","users2.php","editrank.php","editrecord.php","applystores1.php"),
"网络图"=>array("timenet2.php","publicnet.php","dtusers_1.php","tjnets_1.php","glnetedit.php","tjnetedit.php","guanxitu2.php","guanxitu1.php"),
"财务管理"=>array("deltalst.php","delta.php","banks.php","bankadd.php","remits.php","cashes.php","moneyzz.php","e_government.php","/pay/admin_paylist.php"),
"奖金管理"=>array("salarys.php","periodsadd.php","/0123456789/1.php","/0123456789/1_do.php","/0123456789/2.php","/0123456789/pingheng.php","/0123456789/3.php","jjedit.php"),
"查询系统"=>array("hytj.php","hytjquery.php","salaryoutquery.php","userjj.php","salarytj.php"),
"产品管理"=>array("category.php","category1.php","category4.php","category5.php","products.php","productview.php","productadd.php","productin.php","productout.php"),
"订单管理"=>array("orders.php","orderview.php","sendgoods.php","logistics.php","addlog.php"),
"信息中心"=>array("writemail.php","receviewmail.php","mailview.php","sendmail.php","mail1view.php","announces.php","announceadd.php"),
"短信管理"=>array("smsye.php","smsMgr.php","smsset.php","smsdy.php","smsdyadd.php","smsgroup.php","smsgroupadd.php","usergroupadd.php","smsgroupuser.php","smsqf.php","smslst.php"),
"数据库管理"=>array("/snipe_bacwa/DatabaseBackup.php","/snipe_bacwa/DatabaseRestore.php",'DownDatabaseZip.php','ChangePath.php','DatabaseBackupDo.php','phome.php'),
"系统管理"=>array("managers.php","manageradd.php","departments.php","departmentadd.php","logs.php","areaadmin.php","addprovince.php","cityadmin.php","addcity.php","stateadmin.php","addarea.php","setting.php","setting_sys.php","userpower2.php","settingpage.php","changepass.php","cleardata.php"));
$ismenusary	=array(
"会员资料"=>array(1,0,1,1,0,0,0,0,1,1,1,0,1,1),
"网络图"=>array(1,1,1,1,1,1,1,1),
"财务管理"=>array(1,0,1,0,1,1,1,1,1),
"奖金管理"=>array(1,1,0,0,0,0,0,0),
"查询系统"=>array(1,0,1,1,1),
"产品管理"=>array(1,0,0,0,1,0,0,1,1),
"订单管理"=>array(1,0,0,1,0),
"信息中心"=>array(1,1,0,1,0,1,0),
"短信管理"=>array(1,1,1,1,0,1,0,0,0,1,1),
"数据库管理"=>array(1,1,0,0,0,0),
"系统管理"=>array(1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1));

?>