<?php

$sql="select isdp,rank from {$db_prefix}users where username='".$_SESSION['glo_username']."'";
$rs=$db->get_one($sql);
if($glo_gpfs==1){
$powerary=array(
"资料管理"=>array("资料查看","资料修改","密码修改"),
"业务管理"=>array("会员申请","未激活会员","已激活会员","会员升级","申请店铺"),
"网络管理"=>array("一条线","安置网络","推荐网络","推荐树状图"),
"财务管理"=>array("奖金提现","电子货币转出","电子货币转入","汇款通知","内部转账","日奖金查询","月奖金查询","现金钱包","奖金钱包","重消购物账户","报单购物账户","在线支付记录"),
"订单管理"=>array("我要订货","我的购物车","订单查询"),
"信息管理"=>array("系统公告","写邮件","收邮件","发件箱")
);
$filesary=array(
"资料管理"=>array("userview.php","zledit.php","pwdedit.php"),
"业务管理"=>array("userreg.php","myhy11.php","myhy.php","applystore.php","applycenter.php"),
"网络管理"=>array("timenet2.php","dtusers_1.php","tjnets_1.php","guanxitu1.php"),
"财务管理"=>array("txadd.php","moneyzz.php","moneyzz1.php","myremits.php","transfer.php","salaryquery.php","salaryquery1.php","e_government.php","e_government.php?type=4","e_government.php?type=3","e_government.php?type=2","/pay/123.php"),
"订单管理"=>array("order.php","mygoodscart.php","orderlst.php"),
"信息管理"=>array("announces.php","writemail.php","receviewmail.php","sendmail.php")
);
}else{
$powerary=array(
"资料管理"=>array("资料查看","资料修改","密码修改"),
"业务管理"=>array("会员申请","会员升级","申请店铺"),
"网络管理"=>array("公排网","安置网络","推荐网络","推荐树状图"),
"财务管理"=>array("奖金提现","电子货币转出","电子货币转入","汇款通知","内部转账","日奖金查询","月奖金查询","现金钱包","奖金钱包","重消购物账户","报单购物账户","在线支付记录"),
"订单管理"=>array("我要订货","我的购物车","订单查询"),
"信息管理"=>array("系统公告","写邮件","收邮件","发件箱")
);
$filesary=array(
"资料管理"=>array("userview.php","zledit.php","pwdedit.php"),
"业务管理"=>array("userreg.php","applystore.php","applycenter.php"),
"网络管理"=>array("publicnet.php","dtusers_1.php","tjnets_1.php","guanxitu1.php"),
"财务管理"=>array("txadd.php","moneyzz.php","moneyzz1.php","myremits.php","transfer.php","salaryquery.php","salaryquery1.php","e_government.php","e_government.php?type=4","e_government.php?type=3","e_government.php?type=2","/pay/123.php"),
"订单管理"=>array("order.php","mygoodscart.php","orderlst.php"),
"信息管理"=>array("announces.php","writemail.php","receviewmail.php","sendmail.php")
);
}
if($rs['isdp']==1){
$powerary['业务管理'][]="未激活会员";
$filesary['业务管理'][]="myhy11.php";
$powerary['业务管理'][]="已激活会员";
$filesary['业务管理'][]="myhy.php";
}
$powerary111=array(
"资料管理"=>array("资料查看","资料修改","密码修改"),
"业务管理"=>array("会员申请","未激活会员","已激活会员","会员升级","申请店铺"),
"网络管理"=>array("一条线","公排网","安置网络","推荐网络","推荐树状图"),
"财务管理"=>array("奖金提现","电子货币转出","电子货币转入","汇款通知","内部转账","日奖金查询","现金钱包","奖金钱包","重消购物账户","报单购物账户","在线支付记录"),
"订单管理"=>array("我要订货","我的购物车","订单查询"),
"信息管理"=>array("系统公告","写邮件","收邮件","发件箱")
);
?>